services:
  postgres:
    image: postgres:latest
    container_name: blog-postgresdb
    restart: always
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    networks:
      - backend-network

  mongo:
    image: mongo:latest
    container_name: blog-mongodb
    restart: always
    env_file: .env
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: blog-rabbitmq
    env_file: .env
    ports:
      - "15672:15672" # temp
      - "5672:5672" # temp
    networks:
      - backend-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend1:
    build:
      context: ./backend
    container_name: blog-backend-1
    env_file: .env
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - postgres
      - mongo
      - rabbitmq

  backend2:
    build:
      context: ./backend
    container_name: blog-backend-2
    env_file: .env
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - postgres
      - mongo
      - rabbitmq

  backend3:
    build:
      context: ./backend
    container_name: blog-backend-3
    env_file: .env
    networks:
      - frontend-network
      - backend-network
    depends_on:
      - postgres
      - mongo
      - rabbitmq

  balancer:
    build:
      context: ./load-balancer
      target: final
    container_name: blog-balancer
    ports:
      - "8090:8090"
    networks:
      - frontend-network
    depends_on:
      - backend1
      - backend2
      - backend3

  mailer:
    build:
      context: ./mail-service
    container_name: blog-mail-service
    env_file: .env
    networks:
      - backend-network
    depends_on:
      rabbitmq:
        condition: service_healthy

networks:
  frontend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

  backend-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24
          gateway: 172.16.0.1

volumes:
  postgres_data:
  mongo_data:
