services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - '27017:27017'
    restart: always
    env_file:
      - .env
    networks:
      - app-network
  nestjs-app:
    build:
      context: ./backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - mongo
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres_data:
  mongo-data:
